export const MexicoState = [
{city_name: "Acambay"},
{city_name: "Acolman"},
{city_name: "Aculco"},
{city_name: "Almoloya de Alquisiras"},
{city_name: "Almoloya de Juárez"},
{city_name: "Almoloya del Río"},
{city_name: "Amanalco"},
{city_name: "Amatepec"},
{city_name: "Amecameca"},
{city_name: "Apaxco"},
{city_name: "Atenco"},
{city_name: "Atizapán"},
{city_name: "Atizapán de Zaragoza"},
{city_name: "Atlacomulco"},
{city_name: "Atlautla"},
{city_name: "Axapusco"},
{city_name: "Ayapango"},
{city_name: "Calimaya"},
{city_name: "Capulhuac"},
{city_name: "Coacalco de Berriozábal"},
{city_name: "Coatepec Harinas"},
{city_name: "Cocotitlán"},
{city_name: "Coyotepec"},
{city_name: "Cuautitlán"},
{city_name: "Chalco"},
{city_name: "Chapa de Mota"},
{city_name: "Chapultepec"},
{city_name: "Chiautla"},
{city_name: "Chicoloapan"},
{city_name: "Chiconcuac"},
{city_name: "Chimalhuacán"},
{city_name: "Donato Guerra"},
{city_name: "Ecatepec de Morelos"},
{city_name: "Ecatzingo"},
{city_name: "Huehuetoca"},
{city_name: "Hueypoxtla"},
{city_name: "Huixquilucan"},
{city_name: "Isidro Fabela"},
{city_name: "Ixtapaluca"},
{city_name: "Ixtapan de la Sal"},
{city_name: "Ixtapan del Oro"},
{city_name: "Ixtlahuaca"},
{city_name: "Xalatlaco"},
{city_name: "Jaltenco"},
{city_name: "Jilotepec"},
{city_name: "Jilotzingo"},
{city_name: "Jiquipilco"},
{city_name: "Jocotitlán"},
{city_name: "Joquicingo"},
{city_name: "Juchitepec"},
{city_name: "Lerma"},
{city_name: "Malinalco"},
{city_name: "Melchor Ocampo"},
{city_name: "Metepec"},
{city_name: "Mexicaltzingo"},
{city_name: "Morelos"},
{city_name: "Naucalpan de Juárez"},
{city_name: "Nezahualcóyotl"},
{city_name: "Nextlalpan"},
{city_name: "Nicolás Romero"},
{city_name: "Nopaltepec"},
{city_name: "Ocoyoacac"},
{city_name: "Ocuilán"},
{city_name: "El Oro"},
{city_name: "Otumba"},
{city_name: "Otzoloapan"},
{city_name: "Otzolotepec"},
{city_name: "Ozumba"},
{city_name: "Papalotla"},
{city_name: "La Paz"},
{city_name: "Polotitlán"},
{city_name: "Rayón"},
{city_name: "San Antonio la Isla"},
{city_name: "San Felipe del Progreso"},
{city_name: "San Martín de las Pirámides"},
{city_name: "San Mateo Atenco"},
{city_name: "San Simón de Guerrero"},
{city_name: "Santo Tomás"},
{city_name: "Soyaniquilpan de Juárez"},
{city_name: "Sultepec"},
{city_name: "Tecámac"},
{city_name: "Tejupilco"},
{city_name: "Temamatla"},
{city_name: "Temascalapa"},
{city_name: "Temascalcingo"},
{city_name: "Temascaltepec"},
{city_name: "Temoaya"},
{city_name: "Tenancingo"},
{city_name: "Tenango del Aire"},
{city_name: "Tenango del Valle"},
{city_name: "Teoloyucán"},
{city_name: "Teotihuacán"},
{city_name: "Tepetlaoxtoc"},
{city_name: "Tepetlixpa"},
{city_name: "Tepotzotlán"},
{city_name: "Tequixquiac"},
{city_name: "Texcaltitlán"},
{city_name: "Texcalyacac"},
{city_name: "Texcoco"},
{city_name: "Tezoyuca"},
{city_name: "Tianguistenco"},
{city_name: "Timilpan"},
{city_name: "Tlalmanalco"},
{city_name: "Tlalnepantla de Baz"},
{city_name: "Tlatlaya"},
{city_name: "Toluca"},
{city_name: "Tonatico"},
{city_name: "Tultepec"},
{city_name: "Tultitlán"},
{city_name: "Valle de Bravo"},
{city_name: "Villa de Allende"},
{city_name: "Villa del Carbón"},
{city_name: "Villa Guerrero"},
{city_name: "Villa Victoria"},
{city_name: "Xonacatlán"},
{city_name: "Zacazonapan"},
{city_name: "Zacualpan"},
{city_name: "Zinacantepec"},
{city_name: "Zumpahuacán"},
{city_name: "Zumpango"},
{city_name: "Cuautitlán Izcalli"},
{city_name: "Valle de Chalco Solidaridad"},
{city_name: "Luvianos"},
{city_name: "San José del Rincón"},
{city_name: "Tonanitla"},
];
